services:
  mongodb:
    image: mongo:latest
    ports:
      - '${DB_PORT}:27017'
    volumes:
      - dbdata6:/data/db
    networks:
      - node-network

volumes:
  dbdata6:

networks:
  node-network:
    driver: bridge